name: "🐛 Bug Report"
description: Create a report to help us improve
title: "[BUG] "
labels:
  - bug
  - unverified
body:
  - id: description
    type: textarea
    attributes:
      label: Current behaviour
      description: A clear and concise description of what the bug is.
    validations:
      required: false
  - id: steps
    type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - id: expected
    type: textarea
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - id: os
    type: dropdown
    attributes:
      label: OS
      description: OS of device
      options:
        - Windows
        - Linux
        - MacOS
        - Android
        - iOS
        - other
    validations:
      required: false
  - id: browser
    type: dropdown
    attributes:
      label: Browser
      description: Used web browser
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Other Chrome/Chromium based
        - Other
    validations:
      required: false
  - id: version
    type: dropdown
    attributes:
      label: App version
      options:
        - 1.0.0
      default: 0
    validations:
      required: true
  - id: additional
    type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Screenshots? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
